name: Build Typst document
on: [push, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst Compile
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ

      - name: Rename PDF
        run: mv main.pdf TudorAndrei-Dumitrascu-Resume.pdf
